# Generated by Django 5.2.10 on 2026-01-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('windspeed', models.FloatField(blank=True, null=True)),
                ('winddirection', models.FloatField(blank=True, null=True)),
                ('weathercode', models.FloatField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
