# Generated by Django 5.2.10 on 2026-01-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='weather',
            index=models.Index(fields=['synced_at'], name='weather_wea_synced__1ef090_idx'),
        ),
        migrations.AddIndex(
            model_name='weather',
            index=models.Index(fields=['city_name', 'synced_at'], name='weather_wea_city_na_bb8cf1_idx'),
        ),
    ]
