# Generated by Django 5.2.10 on 2026-01-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weather_weather_wea_synced__1ef090_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='weathercode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
